services:

  nginx:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./src/:/var/www/php/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    links:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./src/:/var/www/php/
    expose:
      - 9000


